'use client';

import React, { useState, useCallback, useEffect } from 'react';
import { Youtube, Plus, Trash2, Play, Download, Loader2, AlertCircle, Check, Copy, RefreshCw } from 'lucide-react';
import { Channel } from '@/lib/channels';
import { mapGroupToCategory } from '@/lib/channelUtils';

interface YouTubeChannel {
  id: string;
  videoId: string;
  name: string;
  thumbnail: string;
  hlsUrl: string | null;
  isLive: boolean;
  addedAt: number;
  lastChecked: number;
  error?: string;
}

interface YouTubeManagerProps {
  onAddChannel: (channel: Channel) => void;
  onPlayChannel?: (channel: Channel) => void;
}

const STORAGE_KEY = 'streamvault_youtube_channels';

function loadSavedChannels(): YouTubeChannel[] {
  if (typeof window === 'undefined') return [];
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    return saved ? JSON.parse(saved) : [];
  } catch {
    return [];
  }
}

function saveChannels(channels: YouTubeChannel[]): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(channels));
  } catch {
    console.error('Failed to save YouTube channels');
  }
}

export function YouTubeManager({ onAddChannel, onPlayChannel }: YouTubeManagerProps) {
  const [channels, setChannels] = useState<YouTubeChannel[]>([]);
  const [inputUrl, setInputUrl] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [refreshingId, setRefreshingId] = useState<string | null>(null);

  // Load saved channels on mount
  useEffect(() => {
    setChannels(loadSavedChannels());
  }, []);

  // Save channels when they change
  useEffect(() => {
    if (channels.length > 0) {
      saveChannels(channels);
    }
  }, [channels]);

  const addYouTubeUrl = useCallback(async () => {
    if (!inputUrl.trim()) return;

    setLoading(true);
    setError(null);

    try {
      const response = await fetch(`/api/youtube-extract?url=${encodeURIComponent(inputUrl)}`);
      const data = await response.json();

      if (!response.ok || data.error) {
        setError(data.error || 'Failed to extract YouTube stream');
        return;
      }

      // Check if already added
      if (channels.some(ch => ch.videoId === data.id)) {
        setError('This channel/video is already added');
        return;
      }

      const newChannel: YouTubeChannel = {
        id: `yt-${data.id}-${Date.now()}`,
        videoId: data.id,
        name: data.name,
        thumbnail: data.thumbnail,
        hlsUrl: data.hlsUrl,
        isLive: data.isLive,
        addedAt: Date.now(),
        lastChecked: Date.now(),
        error: data.hlsUrl ? undefined : 'No live stream available',
      };

      setChannels(prev => [...prev, newChannel]);
      setInputUrl('');
    } catch (err) {
      setError('Failed to fetch YouTube data');
    } finally {
      setLoading(false);
    }
  }, [inputUrl, channels]);

  const refreshChannel = useCallback(async (channel: YouTubeChannel) => {
    setRefreshingId(channel.id);

    try {
      const response = await fetch(`/api/youtube-extract?url=https://youtube.com/watch?v=${channel.videoId}`);
      const data = await response.json();

      setChannels(prev => prev.map(ch => {
        if (ch.id === channel.id) {
          return {
            ...ch,
            hlsUrl: data.hlsUrl || null,
            isLive: data.isLive,
            lastChecked: Date.now(),
            error: data.hlsUrl ? undefined : 'No live stream available',
          };
        }
        return ch;
      }));
    } catch {
      // Keep existing data on error
    } finally {
      setRefreshingId(null);
    }
  }, []);

  const removeChannel = useCallback((id: string) => {
    setChannels(prev => {
      const updated = prev.filter(ch => ch.id !== id);
      saveChannels(updated);
      return updated;
    });
  }, []);

  const playChannel = useCallback((channel: YouTubeChannel) => {
    if (!channel.hlsUrl || !onPlayChannel) return;

    const ch: Channel = {
      id: channel.id,
      number: 800 + Math.floor(Math.random() * 100),
      name: channel.name,
      category: mapGroupToCategory(channel.name),
      url: channel.hlsUrl,
    };

    onPlayChannel(ch);
  }, [onPlayChannel]);

  const addToImported = useCallback((channel: YouTubeChannel) => {
    if (!channel.hlsUrl) return;

    const ch: Channel = {
      id: channel.id,
      number: 800 + Math.floor(Math.random() * 100),
      name: channel.name,
      category: mapGroupToCategory(channel.name),
      url: channel.hlsUrl,
    };

    onAddChannel(ch);
  }, [onAddChannel]);

  const generateM3U = useCallback(() => {
    const liveChannels = channels.filter(ch => ch.hlsUrl);
    if (liveChannels.length === 0) return '';

    let m3u = '#EXTM3U\n';
    m3u += '# Generated by StreamVault - YouTube Live Channels\n';
    m3u += `# Generated: ${new Date().toISOString()}\n\n`;

    liveChannels.forEach(ch => {
      const category = mapGroupToCategory(ch.name);
      m3u += `#EXTINF:-1 tvg-id="${ch.videoId}" tvg-name="${ch.name}" tvg-logo="${ch.thumbnail}" group-title="${category}",${ch.name}\n`;
      m3u += `${ch.hlsUrl}\n`;
    });

    return m3u;
  }, [channels]);

  const copyM3U = useCallback(() => {
    const m3u = generateM3U();
    if (!m3u) return;

    navigator.clipboard.writeText(m3u).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [generateM3U]);

  const downloadM3U = useCallback(() => {
    const m3u = generateM3U();
    if (!m3u) return;

    const blob = new Blob([m3u], { type: 'audio/x-mpegurl' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'youtube-live.m3u';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [generateM3U]);

  const liveCount = channels.filter(ch => ch.hlsUrl).length;

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center gap-2 text-red-400">
        <Youtube size={20} />
        <span className="font-medium">YouTube Live Manager</span>
      </div>

      {/* Add URL Input */}
      <div className="space-y-2">
        <div className="flex gap-2">
          <input
            type="text"
            value={inputUrl}
            onChange={(e) => setInputUrl(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && addYouTubeUrl()}
            placeholder="Paste YouTube live stream or channel URL..."
            className="flex-1 px-3 py-2 bg-gray-800 border border-gray-700 rounded-lg text-white placeholder-gray-500 text-sm focus:outline-none focus:ring-2 focus:ring-red-500"
            disabled={loading}
          />
          <button
            onClick={addYouTubeUrl}
            disabled={loading || !inputUrl.trim()}
            className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
          >
            {loading ? <Loader2 size={16} className="animate-spin" /> : <Plus size={16} />}
            Add
          </button>
        </div>
        <p className="text-xs text-gray-500">
          Supports: youtube.com/watch?v=..., youtu.be/..., youtube.com/live/..., youtube.com/@channel/live
        </p>
      </div>

      {/* Error */}
      {error && (
        <div className="flex items-center gap-2 p-3 bg-red-900/30 border border-red-800 rounded-lg text-red-300 text-sm">
          <AlertCircle size={16} />
          {error}
        </div>
      )}

      {/* Channel List */}
      {channels.length > 0 && (
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <span className="text-sm text-gray-400">
              {channels.length} channel{channels.length !== 1 ? 's' : ''} ({liveCount} live)
            </span>
            {liveCount > 0 && (
              <div className="flex gap-2">
                <button
                  onClick={copyM3U}
                  className="flex items-center gap-1 px-2 py-1 text-xs bg-gray-800 text-gray-300 rounded hover:bg-gray-700"
                >
                  {copied ? <Check size={12} /> : <Copy size={12} />}
                  {copied ? 'Copied!' : 'Copy M3U'}
                </button>
                <button
                  onClick={downloadM3U}
                  className="flex items-center gap-1 px-2 py-1 text-xs bg-gray-800 text-gray-300 rounded hover:bg-gray-700"
                >
                  <Download size={12} />
                  Download M3U
                </button>
              </div>
            )}
          </div>

          <div className="max-h-[300px] overflow-y-auto space-y-2 pr-1">
            {channels.map((channel) => (
              <div
                key={channel.id}
                className={`flex items-center gap-3 p-3 rounded-lg transition-colors ${
                  channel.hlsUrl ? 'bg-gray-800' : 'bg-gray-800/50 opacity-60'
                }`}
              >
                {/* Thumbnail */}
                <div className="w-16 h-10 flex-shrink-0 bg-gray-700 rounded overflow-hidden relative">
                  {channel.thumbnail ? (
                    <img
                      src={channel.thumbnail}
                      alt={channel.name}
                      className="w-full h-full object-cover"
                    />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center">
                      <Youtube size={20} className="text-gray-500" />
                    </div>
                  )}
                  {channel.isLive && channel.hlsUrl && (
                    <div className="absolute top-1 right-1 px-1 py-0.5 bg-red-600 rounded text-[8px] font-bold">
                      LIVE
                    </div>
                  )}
                </div>

                {/* Info */}
                <div className="flex-1 min-w-0">
                  <h4 className="font-medium text-white text-sm truncate">{channel.name}</h4>
                  <div className="text-xs text-gray-400">
                    {channel.hlsUrl ? (
                      <span className="text-green-400">Stream available</span>
                    ) : (
                      <span className="text-yellow-400">{channel.error || 'Not live'}</span>
                    )}
                  </div>
                </div>

                {/* Actions */}
                <div className="flex items-center gap-1">
                  <button
                    onClick={() => refreshChannel(channel)}
                    disabled={refreshingId === channel.id}
                    className="p-1.5 text-gray-400 hover:text-white rounded hover:bg-gray-700"
                    title="Refresh"
                  >
                    <RefreshCw size={14} className={refreshingId === channel.id ? 'animate-spin' : ''} />
                  </button>
                  {channel.hlsUrl && (
                    <>
                      {onPlayChannel && (
                        <button
                          onClick={() => playChannel(channel)}
                          className="p-1.5 bg-green-600 text-white rounded hover:bg-green-700"
                          title="Play"
                        >
                          <Play size={14} />
                        </button>
                      )}
                      <button
                        onClick={() => addToImported(channel)}
                        className="p-1.5 bg-blue-600 text-white rounded hover:bg-blue-700"
                        title="Add to channels"
                      >
                        <Plus size={14} />
                      </button>
                    </>
                  )}
                  <button
                    onClick={() => removeChannel(channel.id)}
                    className="p-1.5 text-red-400 hover:text-red-300 rounded hover:bg-gray-700"
                    title="Remove"
                  >
                    <Trash2 size={14} />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Empty State */}
      {channels.length === 0 && (
        <div className="text-center py-6 text-gray-400">
          <Youtube size={32} className="mx-auto mb-2 opacity-50" />
          <p className="text-sm">Add YouTube live streams to create your playlist</p>
          <p className="text-xs mt-1">Paste a YouTube URL above to get started</p>
        </div>
      )}
    </div>
  );
}
